### ISSUE TITLE
Błąd połączenia z serwerem! Spróbuj ponownie.

### ISSUE THREAD

**Issue by BartoszMichalak13** [KN-Algo/fabryki-i-magazyny#1]
Nie mogę odpalić apki, błąd jak w temacie, ponieżej output z konsoli
Output:
PHP Fatal error:  Uncaught Error: Class "SQLite3" not found in /home/bamichal/Algo/fabryki-i-magazyny/backend/Database.php:8
Stack trace:
#0 /home/bamichal/Algo/fabryki-i-magazyny/backend/api/validateUser.php(5): Database->__construct()
#1 {main}
  thrown in /home/bamichal/Algo/fabryki-i-magazyny/backend/Database.php on line 8
[Mon Oct  7 19:29:15 2024] 127.0.0.1:47346 [500]: POST /backend/api/validateUser.php - Uncaught Error: Class "SQLite3" not found in /home/bamichal/Algo/fabryki-i-magazyny/backend/Database.php:8
Stack trace:
#0 /home/bamichal/Algo/fabryki-i-magazyny/backend/api/validateUser.php(5): Database->__construct()
#1 {main}
  thrown in /home/bamichal/Algo/fabryki-i-magazyny/backend/Database.php on line 8
[Mon Oct  7 19:29:15 2024] 127.0.0.1:47346 Closing

**Comment by xEdziu** [comment]
@BartoszMichalak13 a czy mógłbyś proszę pokazać mi strukturę plików Twojego projektu?

**Comment by xEdziu** [comment]
I drugie pytanie - czy włączyłeś moduł `sqlite` w pliku `php.ini`? - [how to](https://stackoverflow.com/questions/70328446/how-do-i-install-or-activate-sqlite3-for-php) - bo jeśli to wynika z nowych konfiguracji, poprawię tutorial odnośnie odpalania programu

**Comment by xEdziu** [comment]
Odpowiedzią była jedna komenda (@BartoszMichalak13 pracował na linuxie): `sudo apt install php-sqlite3`
