### ISSUE TITLE
Można postawić 4 magazyny 1 na drugim

### ISSUE THREAD

**Issue by BartoszMichalak13** [KN-Algo/fabryki-i-magazyny#2]

**Comment by xEdziu** [comment]
Dzięki za informacje!

**Comment by xEdziu** [comment]
![image](https://github.com/user-attachments/assets/a02599f8-8eae-4678-ab4e-6105686911f4)

Już jest to wykrywane zarówno na połączeniu fabryka+magazyn oraz na samych magazynach
